apiVersion: v1
kind: Service
metadata:
  name: go-sidecar-example-headless
  namespace: serhs-mdh
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/instance: go-sidecar-example
    app.kubernetes.io/name: go-sidecar-example
  ports:
    - name: service-port
      port: 8080